create table backroom_users
(
    id bigint generated by default as identity
        constraint backroom_users_pkey
        primary key,
    username varchar not null
        constraint backroom_users_username_key
        unique,
    password varchar not null
);

alter table backroom_users owner to wedding;

create table invitee_parties
(
    id bigint generated by default as identity
        constraint invitee_parties_pkey
        primary key,
    name varchar not null,
    code varchar not null
        constraint invitee_parties_code_key
        unique
);

alter table invitee_parties owner to wedding;

create table invitees
(
    id bigint generated by default as identity
        constraint invitees_pkey
        primary key,
    name varchar not null,
    is_child boolean,
    has_plus_one boolean not null,
    is_bridesmaid boolean not null,
    is_groomsman boolean not null,
    plus_one_name varchar,
    phone varchar,
    email varchar,
    address_line_1 varchar,
    address_line_2 varchar,
    address_city varchar,
    address_state varchar,
    address_postal_code varchar,
    address_country varchar,
    rsvp_response boolean,
    invitee_party_invitees bigint
        constraint invitees_invitee_parties_invitees
        references invitee_parties
        on delete set null
);

alter table invitees owner to wedding;

