// Code generated by entc, DO NOT EDIT.

package event

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeRsvps holds the string denoting the rsvps edge name in mutations.
	EdgeRsvps = "rsvps"
	// Table holds the table name of the event in the database.
	Table = "events"
	// RsvpsTable is the table the holds the rsvps relation/edge.
	RsvpsTable = "event_rsvps"
	// RsvpsInverseTable is the table name for the EventRSVP entity.
	// It exists in this package in order to avoid circular dependency with the "eventrsvp" package.
	RsvpsInverseTable = "event_rsvps"
	// RsvpsColumn is the table column denoting the rsvps relation/edge.
	RsvpsColumn = "event_rsvps"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
