// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InviteesColumns holds the columns for the "invitees" table.
	InviteesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "is_child", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "has_plus_one", Type: field.TypeBool, Default: false},
		{Name: "is_bridesmaid", Type: field.TypeBool, Default: false},
		{Name: "is_groomsman", Type: field.TypeBool, Default: false},
		{Name: "plus_one_name", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "address_line_1", Type: field.TypeString, Nullable: true},
		{Name: "address_line_2", Type: field.TypeString, Nullable: true},
		{Name: "address_city", Type: field.TypeString, Nullable: true},
		{Name: "address_state", Type: field.TypeString, Nullable: true},
		{Name: "address_postal_code", Type: field.TypeString, Nullable: true},
		{Name: "address_country", Type: field.TypeString, Nullable: true},
		{Name: "rsvp_response", Type: field.TypeBool, Nullable: true},
		{Name: "invitee_party_invitees", Type: field.TypeInt, Nullable: true},
	}
	// InviteesTable holds the schema information for the "invitees" table.
	InviteesTable = &schema.Table{
		Name:       "invitees",
		Columns:    InviteesColumns,
		PrimaryKey: []*schema.Column{InviteesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invitees_invitee_parties_invitees",
				Columns:    []*schema.Column{InviteesColumns[16]},
				RefColumns: []*schema.Column{InviteePartiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// InviteePartiesColumns holds the columns for the "invitee_parties" table.
	InviteePartiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 10},
	}
	// InviteePartiesTable holds the schema information for the "invitee_parties" table.
	InviteePartiesTable = &schema.Table{
		Name:        "invitee_parties",
		Columns:     InviteePartiesColumns,
		PrimaryKey:  []*schema.Column{InviteePartiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InviteesTable,
		InviteePartiesTable,
	}
)

func init() {
	InviteesTable.ForeignKeys[0].RefTable = InviteePartiesTable
}
