// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"wedding/ent/backroomuser"
	"wedding/ent/predicate"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// BackroomUserDelete is the builder for deleting a BackroomUser entity.
type BackroomUserDelete struct {
	config
	hooks    []Hook
	mutation *BackroomUserMutation
}

// Where adds a new predicate to the BackroomUserDelete builder.
func (bud *BackroomUserDelete) Where(ps ...predicate.BackroomUser) *BackroomUserDelete {
	bud.mutation.predicates = append(bud.mutation.predicates, ps...)
	return bud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bud *BackroomUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bud.hooks) == 0 {
		affected, err = bud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BackroomUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bud.mutation = mutation
			affected, err = bud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bud.hooks) - 1; i >= 0; i-- {
			mut = bud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (bud *BackroomUserDelete) ExecX(ctx context.Context) int {
	n, err := bud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bud *BackroomUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: backroomuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: backroomuser.FieldID,
			},
		},
	}
	if ps := bud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, bud.driver, _spec)
}

// BackroomUserDeleteOne is the builder for deleting a single BackroomUser entity.
type BackroomUserDeleteOne struct {
	bud *BackroomUserDelete
}

// Exec executes the deletion query.
func (budo *BackroomUserDeleteOne) Exec(ctx context.Context) error {
	n, err := budo.bud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{backroomuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (budo *BackroomUserDeleteOne) ExecX(ctx context.Context) {
	budo.bud.ExecX(ctx)
}
