// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"wedding/ent/backroomuser"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// BackroomUserCreate is the builder for creating a BackroomUser entity.
type BackroomUserCreate struct {
	config
	mutation *BackroomUserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (buc *BackroomUserCreate) SetUsername(s string) *BackroomUserCreate {
	buc.mutation.SetUsername(s)
	return buc
}

// SetPassword sets the "password" field.
func (buc *BackroomUserCreate) SetPassword(s string) *BackroomUserCreate {
	buc.mutation.SetPassword(s)
	return buc
}

// Mutation returns the BackroomUserMutation object of the builder.
func (buc *BackroomUserCreate) Mutation() *BackroomUserMutation {
	return buc.mutation
}

// Save creates the BackroomUser in the database.
func (buc *BackroomUserCreate) Save(ctx context.Context) (*BackroomUser, error) {
	var (
		err  error
		node *BackroomUser
	)
	if len(buc.hooks) == 0 {
		if err = buc.check(); err != nil {
			return nil, err
		}
		node, err = buc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BackroomUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = buc.check(); err != nil {
				return nil, err
			}
			buc.mutation = mutation
			node, err = buc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buc.hooks) - 1; i >= 0; i-- {
			mut = buc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (buc *BackroomUserCreate) SaveX(ctx context.Context) *BackroomUser {
	v, err := buc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (buc *BackroomUserCreate) check() error {
	if _, ok := buc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New("ent: missing required field \"username\"")}
	}
	if v, ok := buc.mutation.Username(); ok {
		if err := backroomuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf("ent: validator failed for field \"username\": %w", err)}
		}
	}
	if _, ok := buc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New("ent: missing required field \"password\"")}
	}
	if v, ok := buc.mutation.Password(); ok {
		if err := backroomuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf("ent: validator failed for field \"password\": %w", err)}
		}
	}
	return nil
}

func (buc *BackroomUserCreate) sqlSave(ctx context.Context) (*BackroomUser, error) {
	_node, _spec := buc.createSpec()
	if err := sqlgraph.CreateNode(ctx, buc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (buc *BackroomUserCreate) createSpec() (*BackroomUser, *sqlgraph.CreateSpec) {
	var (
		_node = &BackroomUser{config: buc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: backroomuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: backroomuser.FieldID,
			},
		}
	)
	if value, ok := buc.mutation.Username(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: backroomuser.FieldUsername,
		})
		_node.Username = value
	}
	if value, ok := buc.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: backroomuser.FieldPassword,
		})
		_node.Password = value
	}
	return _node, _spec
}

// BackroomUserCreateBulk is the builder for creating many BackroomUser entities in bulk.
type BackroomUserCreateBulk struct {
	config
	builders []*BackroomUserCreate
}

// Save creates the BackroomUser entities in the database.
func (bucb *BackroomUserCreateBulk) Save(ctx context.Context) ([]*BackroomUser, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bucb.builders))
	nodes := make([]*BackroomUser, len(bucb.builders))
	mutators := make([]Mutator, len(bucb.builders))
	for i := range bucb.builders {
		func(i int, root context.Context) {
			builder := bucb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BackroomUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bucb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bucb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bucb *BackroomUserCreateBulk) SaveX(ctx context.Context) []*BackroomUser {
	v, err := bucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
