// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"wedding/ent/backroomuser"
	"wedding/ent/predicate"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// BackroomUserQuery is the builder for querying BackroomUser entities.
type BackroomUserQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	fields     []string
	predicates []predicate.BackroomUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BackroomUserQuery builder.
func (buq *BackroomUserQuery) Where(ps ...predicate.BackroomUser) *BackroomUserQuery {
	buq.predicates = append(buq.predicates, ps...)
	return buq
}

// Limit adds a limit step to the query.
func (buq *BackroomUserQuery) Limit(limit int) *BackroomUserQuery {
	buq.limit = &limit
	return buq
}

// Offset adds an offset step to the query.
func (buq *BackroomUserQuery) Offset(offset int) *BackroomUserQuery {
	buq.offset = &offset
	return buq
}

// Order adds an order step to the query.
func (buq *BackroomUserQuery) Order(o ...OrderFunc) *BackroomUserQuery {
	buq.order = append(buq.order, o...)
	return buq
}

// First returns the first BackroomUser entity from the query.
// Returns a *NotFoundError when no BackroomUser was found.
func (buq *BackroomUserQuery) First(ctx context.Context) (*BackroomUser, error) {
	nodes, err := buq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{backroomuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (buq *BackroomUserQuery) FirstX(ctx context.Context) *BackroomUser {
	node, err := buq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BackroomUser ID from the query.
// Returns a *NotFoundError when no BackroomUser ID was found.
func (buq *BackroomUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = buq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{backroomuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (buq *BackroomUserQuery) FirstIDX(ctx context.Context) int {
	id, err := buq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BackroomUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one BackroomUser entity is not found.
// Returns a *NotFoundError when no BackroomUser entities are found.
func (buq *BackroomUserQuery) Only(ctx context.Context) (*BackroomUser, error) {
	nodes, err := buq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{backroomuser.Label}
	default:
		return nil, &NotSingularError{backroomuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (buq *BackroomUserQuery) OnlyX(ctx context.Context) *BackroomUser {
	node, err := buq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BackroomUser ID in the query.
// Returns a *NotSingularError when exactly one BackroomUser ID is not found.
// Returns a *NotFoundError when no entities are found.
func (buq *BackroomUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = buq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = &NotSingularError{backroomuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (buq *BackroomUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := buq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BackroomUsers.
func (buq *BackroomUserQuery) All(ctx context.Context) ([]*BackroomUser, error) {
	if err := buq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return buq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (buq *BackroomUserQuery) AllX(ctx context.Context) []*BackroomUser {
	nodes, err := buq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BackroomUser IDs.
func (buq *BackroomUserQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := buq.Select(backroomuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (buq *BackroomUserQuery) IDsX(ctx context.Context) []int {
	ids, err := buq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (buq *BackroomUserQuery) Count(ctx context.Context) (int, error) {
	if err := buq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return buq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (buq *BackroomUserQuery) CountX(ctx context.Context) int {
	count, err := buq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (buq *BackroomUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := buq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return buq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (buq *BackroomUserQuery) ExistX(ctx context.Context) bool {
	exist, err := buq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BackroomUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (buq *BackroomUserQuery) Clone() *BackroomUserQuery {
	if buq == nil {
		return nil
	}
	return &BackroomUserQuery{
		config:     buq.config,
		limit:      buq.limit,
		offset:     buq.offset,
		order:      append([]OrderFunc{}, buq.order...),
		predicates: append([]predicate.BackroomUser{}, buq.predicates...),
		// clone intermediate query.
		sql:  buq.sql.Clone(),
		path: buq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BackroomUser.Query().
//		GroupBy(backroomuser.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (buq *BackroomUserQuery) GroupBy(field string, fields ...string) *BackroomUserGroupBy {
	group := &BackroomUserGroupBy{config: buq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := buq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return buq.sqlQuery(), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.BackroomUser.Query().
//		Select(backroomuser.FieldUsername).
//		Scan(ctx, &v)
//
func (buq *BackroomUserQuery) Select(field string, fields ...string) *BackroomUserSelect {
	buq.fields = append([]string{field}, fields...)
	return &BackroomUserSelect{BackroomUserQuery: buq}
}

func (buq *BackroomUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range buq.fields {
		if !backroomuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if buq.path != nil {
		prev, err := buq.path(ctx)
		if err != nil {
			return err
		}
		buq.sql = prev
	}
	return nil
}

func (buq *BackroomUserQuery) sqlAll(ctx context.Context) ([]*BackroomUser, error) {
	var (
		nodes = []*BackroomUser{}
		_spec = buq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &BackroomUser{config: buq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, buq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (buq *BackroomUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := buq.querySpec()
	return sqlgraph.CountNodes(ctx, buq.driver, _spec)
}

func (buq *BackroomUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := buq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (buq *BackroomUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   backroomuser.Table,
			Columns: backroomuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: backroomuser.FieldID,
			},
		},
		From:   buq.sql,
		Unique: true,
	}
	if fields := buq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backroomuser.FieldID)
		for i := range fields {
			if fields[i] != backroomuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := buq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := buq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := buq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := buq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, backroomuser.ValidColumn)
			}
		}
	}
	return _spec
}

func (buq *BackroomUserQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(buq.driver.Dialect())
	t1 := builder.Table(backroomuser.Table)
	selector := builder.Select(t1.Columns(backroomuser.Columns...)...).From(t1)
	if buq.sql != nil {
		selector = buq.sql
		selector.Select(selector.Columns(backroomuser.Columns...)...)
	}
	for _, p := range buq.predicates {
		p(selector)
	}
	for _, p := range buq.order {
		p(selector, backroomuser.ValidColumn)
	}
	if offset := buq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := buq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BackroomUserGroupBy is the group-by builder for BackroomUser entities.
type BackroomUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bugb *BackroomUserGroupBy) Aggregate(fns ...AggregateFunc) *BackroomUserGroupBy {
	bugb.fns = append(bugb.fns, fns...)
	return bugb
}

// Scan applies the group-by query and scans the result into the given value.
func (bugb *BackroomUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := bugb.path(ctx)
	if err != nil {
		return err
	}
	bugb.sql = query
	return bugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := bugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (bugb *BackroomUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(bugb.fields) > 1 {
		return nil, errors.New("ent: BackroomUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := bugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := bugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bugb *BackroomUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = fmt.Errorf("ent: BackroomUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) StringX(ctx context.Context) string {
	v, err := bugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (bugb *BackroomUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(bugb.fields) > 1 {
		return nil, errors.New("ent: BackroomUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := bugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := bugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bugb *BackroomUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = fmt.Errorf("ent: BackroomUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) IntX(ctx context.Context) int {
	v, err := bugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (bugb *BackroomUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(bugb.fields) > 1 {
		return nil, errors.New("ent: BackroomUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := bugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := bugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bugb *BackroomUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = fmt.Errorf("ent: BackroomUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := bugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (bugb *BackroomUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(bugb.fields) > 1 {
		return nil, errors.New("ent: BackroomUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := bugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := bugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (bugb *BackroomUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = fmt.Errorf("ent: BackroomUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bugb *BackroomUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := bugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bugb *BackroomUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range bugb.fields {
		if !backroomuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := bugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bugb *BackroomUserGroupBy) sqlQuery() *sql.Selector {
	selector := bugb.sql
	columns := make([]string, 0, len(bugb.fields)+len(bugb.fns))
	columns = append(columns, bugb.fields...)
	for _, fn := range bugb.fns {
		columns = append(columns, fn(selector, backroomuser.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(bugb.fields...)
}

// BackroomUserSelect is the builder for selecting fields of BackroomUser entities.
type BackroomUserSelect struct {
	*BackroomUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (bus *BackroomUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := bus.prepareQuery(ctx); err != nil {
		return err
	}
	bus.sql = bus.BackroomUserQuery.sqlQuery()
	return bus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (bus *BackroomUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := bus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (bus *BackroomUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(bus.fields) > 1 {
		return nil, errors.New("ent: BackroomUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := bus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (bus *BackroomUserSelect) StringsX(ctx context.Context) []string {
	v, err := bus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (bus *BackroomUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = bus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = fmt.Errorf("ent: BackroomUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (bus *BackroomUserSelect) StringX(ctx context.Context) string {
	v, err := bus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (bus *BackroomUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(bus.fields) > 1 {
		return nil, errors.New("ent: BackroomUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := bus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (bus *BackroomUserSelect) IntsX(ctx context.Context) []int {
	v, err := bus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (bus *BackroomUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = bus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = fmt.Errorf("ent: BackroomUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (bus *BackroomUserSelect) IntX(ctx context.Context) int {
	v, err := bus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (bus *BackroomUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(bus.fields) > 1 {
		return nil, errors.New("ent: BackroomUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := bus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (bus *BackroomUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := bus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (bus *BackroomUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = bus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = fmt.Errorf("ent: BackroomUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (bus *BackroomUserSelect) Float64X(ctx context.Context) float64 {
	v, err := bus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (bus *BackroomUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(bus.fields) > 1 {
		return nil, errors.New("ent: BackroomUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := bus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (bus *BackroomUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := bus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (bus *BackroomUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = bus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{backroomuser.Label}
	default:
		err = fmt.Errorf("ent: BackroomUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (bus *BackroomUserSelect) BoolX(ctx context.Context) bool {
	v, err := bus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bus *BackroomUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := bus.sqlQuery().Query()
	if err := bus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bus *BackroomUserSelect) sqlQuery() sql.Querier {
	selector := bus.sql
	selector.Select(selector.Columns(bus.fields...)...)
	return selector
}
