// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"wedding/ent/eventrsvp"
	"wedding/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventRSVPDelete is the builder for deleting a EventRSVP entity.
type EventRSVPDelete struct {
	config
	hooks    []Hook
	mutation *EventRSVPMutation
}

// Where adds a new predicate to the EventRSVPDelete builder.
func (erd *EventRSVPDelete) Where(ps ...predicate.EventRSVP) *EventRSVPDelete {
	erd.mutation.predicates = append(erd.mutation.predicates, ps...)
	return erd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (erd *EventRSVPDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(erd.hooks) == 0 {
		affected, err = erd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventRSVPMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			erd.mutation = mutation
			affected, err = erd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(erd.hooks) - 1; i >= 0; i-- {
			mut = erd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, erd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (erd *EventRSVPDelete) ExecX(ctx context.Context) int {
	n, err := erd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (erd *EventRSVPDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: eventrsvp.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: eventrsvp.FieldID,
			},
		},
	}
	if ps := erd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, erd.driver, _spec)
}

// EventRSVPDeleteOne is the builder for deleting a single EventRSVP entity.
type EventRSVPDeleteOne struct {
	erd *EventRSVPDelete
}

// Exec executes the deletion query.
func (erdo *EventRSVPDeleteOne) Exec(ctx context.Context) error {
	n, err := erdo.erd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventrsvp.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (erdo *EventRSVPDeleteOne) ExecX(ctx context.Context) {
	erdo.erd.ExecX(ctx)
}
