// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"wedding/ent/invitee"
	"wedding/ent/inviteeparty"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// InviteeCreate is the builder for creating a Invitee entity.
type InviteeCreate struct {
	config
	mutation *InviteeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ic *InviteeCreate) SetName(s string) *InviteeCreate {
	ic.mutation.SetName(s)
	return ic
}

// SetIsChild sets the "is_child" field.
func (ic *InviteeCreate) SetIsChild(b bool) *InviteeCreate {
	ic.mutation.SetIsChild(b)
	return ic
}

// SetNillableIsChild sets the "is_child" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableIsChild(b *bool) *InviteeCreate {
	if b != nil {
		ic.SetIsChild(*b)
	}
	return ic
}

// SetHasPlusOne sets the "has_plus_one" field.
func (ic *InviteeCreate) SetHasPlusOne(b bool) *InviteeCreate {
	ic.mutation.SetHasPlusOne(b)
	return ic
}

// SetNillableHasPlusOne sets the "has_plus_one" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableHasPlusOne(b *bool) *InviteeCreate {
	if b != nil {
		ic.SetHasPlusOne(*b)
	}
	return ic
}

// SetPlusOneName sets the "plus_one_name" field.
func (ic *InviteeCreate) SetPlusOneName(s string) *InviteeCreate {
	ic.mutation.SetPlusOneName(s)
	return ic
}

// SetNillablePlusOneName sets the "plus_one_name" field if the given value is not nil.
func (ic *InviteeCreate) SetNillablePlusOneName(s *string) *InviteeCreate {
	if s != nil {
		ic.SetPlusOneName(*s)
	}
	return ic
}

// SetPhone sets the "phone" field.
func (ic *InviteeCreate) SetPhone(s string) *InviteeCreate {
	ic.mutation.SetPhone(s)
	return ic
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (ic *InviteeCreate) SetNillablePhone(s *string) *InviteeCreate {
	if s != nil {
		ic.SetPhone(*s)
	}
	return ic
}

// SetEmail sets the "email" field.
func (ic *InviteeCreate) SetEmail(s string) *InviteeCreate {
	ic.mutation.SetEmail(s)
	return ic
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableEmail(s *string) *InviteeCreate {
	if s != nil {
		ic.SetEmail(*s)
	}
	return ic
}

// SetAddressLine1 sets the "address_line_1" field.
func (ic *InviteeCreate) SetAddressLine1(s string) *InviteeCreate {
	ic.mutation.SetAddressLine1(s)
	return ic
}

// SetNillableAddressLine1 sets the "address_line_1" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableAddressLine1(s *string) *InviteeCreate {
	if s != nil {
		ic.SetAddressLine1(*s)
	}
	return ic
}

// SetAddressLine2 sets the "address_line_2" field.
func (ic *InviteeCreate) SetAddressLine2(s string) *InviteeCreate {
	ic.mutation.SetAddressLine2(s)
	return ic
}

// SetNillableAddressLine2 sets the "address_line_2" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableAddressLine2(s *string) *InviteeCreate {
	if s != nil {
		ic.SetAddressLine2(*s)
	}
	return ic
}

// SetAddressCity sets the "address_city" field.
func (ic *InviteeCreate) SetAddressCity(s string) *InviteeCreate {
	ic.mutation.SetAddressCity(s)
	return ic
}

// SetNillableAddressCity sets the "address_city" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableAddressCity(s *string) *InviteeCreate {
	if s != nil {
		ic.SetAddressCity(*s)
	}
	return ic
}

// SetAddressState sets the "address_state" field.
func (ic *InviteeCreate) SetAddressState(s string) *InviteeCreate {
	ic.mutation.SetAddressState(s)
	return ic
}

// SetNillableAddressState sets the "address_state" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableAddressState(s *string) *InviteeCreate {
	if s != nil {
		ic.SetAddressState(*s)
	}
	return ic
}

// SetAddressPostalCode sets the "address_postal_code" field.
func (ic *InviteeCreate) SetAddressPostalCode(s string) *InviteeCreate {
	ic.mutation.SetAddressPostalCode(s)
	return ic
}

// SetNillableAddressPostalCode sets the "address_postal_code" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableAddressPostalCode(s *string) *InviteeCreate {
	if s != nil {
		ic.SetAddressPostalCode(*s)
	}
	return ic
}

// SetAddressCountry sets the "address_country" field.
func (ic *InviteeCreate) SetAddressCountry(s string) *InviteeCreate {
	ic.mutation.SetAddressCountry(s)
	return ic
}

// SetNillableAddressCountry sets the "address_country" field if the given value is not nil.
func (ic *InviteeCreate) SetNillableAddressCountry(s *string) *InviteeCreate {
	if s != nil {
		ic.SetAddressCountry(*s)
	}
	return ic
}

// SetPartyID sets the "party" edge to the InviteeParty entity by ID.
func (ic *InviteeCreate) SetPartyID(id int) *InviteeCreate {
	ic.mutation.SetPartyID(id)
	return ic
}

// SetNillablePartyID sets the "party" edge to the InviteeParty entity by ID if the given value is not nil.
func (ic *InviteeCreate) SetNillablePartyID(id *int) *InviteeCreate {
	if id != nil {
		ic = ic.SetPartyID(*id)
	}
	return ic
}

// SetParty sets the "party" edge to the InviteeParty entity.
func (ic *InviteeCreate) SetParty(i *InviteeParty) *InviteeCreate {
	return ic.SetPartyID(i.ID)
}

// Mutation returns the InviteeMutation object of the builder.
func (ic *InviteeCreate) Mutation() *InviteeMutation {
	return ic.mutation
}

// Save creates the Invitee in the database.
func (ic *InviteeCreate) Save(ctx context.Context) (*Invitee, error) {
	var (
		err  error
		node *Invitee
	)
	ic.defaults()
	if len(ic.hooks) == 0 {
		if err = ic.check(); err != nil {
			return nil, err
		}
		node, err = ic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InviteeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ic.check(); err != nil {
				return nil, err
			}
			ic.mutation = mutation
			node, err = ic.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ic.hooks) - 1; i >= 0; i-- {
			mut = ic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InviteeCreate) SaveX(ctx context.Context) *Invitee {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (ic *InviteeCreate) defaults() {
	if _, ok := ic.mutation.IsChild(); !ok {
		v := invitee.DefaultIsChild
		ic.mutation.SetIsChild(v)
	}
	if _, ok := ic.mutation.HasPlusOne(); !ok {
		v := invitee.DefaultHasPlusOne
		ic.mutation.SetHasPlusOne(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InviteeCreate) check() error {
	if _, ok := ic.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := ic.mutation.Name(); ok {
		if err := invitee.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if _, ok := ic.mutation.HasPlusOne(); !ok {
		return &ValidationError{Name: "has_plus_one", err: errors.New("ent: missing required field \"has_plus_one\"")}
	}
	return nil
}

func (ic *InviteeCreate) sqlSave(ctx context.Context) (*Invitee, error) {
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ic *InviteeCreate) createSpec() (*Invitee, *sqlgraph.CreateSpec) {
	var (
		_node = &Invitee{config: ic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: invitee.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: invitee.FieldID,
			},
		}
	)
	if value, ok := ic.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldName,
		})
		_node.Name = value
	}
	if value, ok := ic.mutation.IsChild(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: invitee.FieldIsChild,
		})
		_node.IsChild = &value
	}
	if value, ok := ic.mutation.HasPlusOne(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: invitee.FieldHasPlusOne,
		})
		_node.HasPlusOne = value
	}
	if value, ok := ic.mutation.PlusOneName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldPlusOneName,
		})
		_node.PlusOneName = &value
	}
	if value, ok := ic.mutation.Phone(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldPhone,
		})
		_node.Phone = &value
	}
	if value, ok := ic.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldEmail,
		})
		_node.Email = &value
	}
	if value, ok := ic.mutation.AddressLine1(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldAddressLine1,
		})
		_node.AddressLine1 = &value
	}
	if value, ok := ic.mutation.AddressLine2(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldAddressLine2,
		})
		_node.AddressLine2 = &value
	}
	if value, ok := ic.mutation.AddressCity(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldAddressCity,
		})
		_node.AddressCity = &value
	}
	if value, ok := ic.mutation.AddressState(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldAddressState,
		})
		_node.AddressState = &value
	}
	if value, ok := ic.mutation.AddressPostalCode(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldAddressPostalCode,
		})
		_node.AddressPostalCode = &value
	}
	if value, ok := ic.mutation.AddressCountry(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: invitee.FieldAddressCountry,
		})
		_node.AddressCountry = &value
	}
	if nodes := ic.mutation.PartyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitee.PartyTable,
			Columns: []string{invitee.PartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: inviteeparty.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InviteeCreateBulk is the builder for creating many Invitee entities in bulk.
type InviteeCreateBulk struct {
	config
	builders []*InviteeCreate
}

// Save creates the Invitee entities in the database.
func (icb *InviteeCreateBulk) Save(ctx context.Context) ([]*Invitee, error) {
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Invitee, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InviteeCreateBulk) SaveX(ctx context.Context) []*Invitee {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
