// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"wedding/ent/inviteeparty"
	"wedding/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InviteePartyDelete is the builder for deleting a InviteeParty entity.
type InviteePartyDelete struct {
	config
	hooks    []Hook
	mutation *InviteePartyMutation
}

// Where adds a new predicate to the InviteePartyDelete builder.
func (ipd *InviteePartyDelete) Where(ps ...predicate.InviteeParty) *InviteePartyDelete {
	ipd.mutation.predicates = append(ipd.mutation.predicates, ps...)
	return ipd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ipd *InviteePartyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ipd.hooks) == 0 {
		affected, err = ipd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InviteePartyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ipd.mutation = mutation
			affected, err = ipd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ipd.hooks) - 1; i >= 0; i-- {
			mut = ipd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ipd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipd *InviteePartyDelete) ExecX(ctx context.Context) int {
	n, err := ipd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ipd *InviteePartyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: inviteeparty.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: inviteeparty.FieldID,
			},
		},
	}
	if ps := ipd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ipd.driver, _spec)
}

// InviteePartyDeleteOne is the builder for deleting a single InviteeParty entity.
type InviteePartyDeleteOne struct {
	ipd *InviteePartyDelete
}

// Exec executes the deletion query.
func (ipdo *InviteePartyDeleteOne) Exec(ctx context.Context) error {
	n, err := ipdo.ipd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{inviteeparty.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ipdo *InviteePartyDeleteOne) ExecX(ctx context.Context) {
	ipdo.ipd.ExecX(ctx)
}
