// Code generated by entc, DO NOT EDIT.

package ent

import (
	"wedding/ent/event"
	"wedding/ent/invitee"
	"wedding/ent/inviteeparty"
	"wedding/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescName is the schema descriptor for name field.
	eventDescName := eventFields[0].Descriptor()
	// event.NameValidator is a validator for the "name" field. It is called by the builders before save.
	event.NameValidator = eventDescName.Validators[0].(func(string) error)
	inviteeFields := schema.Invitee{}.Fields()
	_ = inviteeFields
	// inviteeDescName is the schema descriptor for name field.
	inviteeDescName := inviteeFields[0].Descriptor()
	// invitee.NameValidator is a validator for the "name" field. It is called by the builders before save.
	invitee.NameValidator = inviteeDescName.Validators[0].(func(string) error)
	// inviteeDescIsChild is the schema descriptor for is_child field.
	inviteeDescIsChild := inviteeFields[1].Descriptor()
	// invitee.DefaultIsChild holds the default value on creation for the is_child field.
	invitee.DefaultIsChild = inviteeDescIsChild.Default.(bool)
	// inviteeDescHasPlusOne is the schema descriptor for has_plus_one field.
	inviteeDescHasPlusOne := inviteeFields[2].Descriptor()
	// invitee.DefaultHasPlusOne holds the default value on creation for the has_plus_one field.
	invitee.DefaultHasPlusOne = inviteeDescHasPlusOne.Default.(bool)
	// inviteeDescIsBridesmaid is the schema descriptor for is_bridesmaid field.
	inviteeDescIsBridesmaid := inviteeFields[3].Descriptor()
	// invitee.DefaultIsBridesmaid holds the default value on creation for the is_bridesmaid field.
	invitee.DefaultIsBridesmaid = inviteeDescIsBridesmaid.Default.(bool)
	// inviteeDescIsGroomsman is the schema descriptor for is_groomsman field.
	inviteeDescIsGroomsman := inviteeFields[4].Descriptor()
	// invitee.DefaultIsGroomsman holds the default value on creation for the is_groomsman field.
	invitee.DefaultIsGroomsman = inviteeDescIsGroomsman.Default.(bool)
	inviteepartyFields := schema.InviteeParty{}.Fields()
	_ = inviteepartyFields
	// inviteepartyDescName is the schema descriptor for name field.
	inviteepartyDescName := inviteepartyFields[0].Descriptor()
	// inviteeparty.NameValidator is a validator for the "name" field. It is called by the builders before save.
	inviteeparty.NameValidator = inviteepartyDescName.Validators[0].(func(string) error)
	// inviteepartyDescCode is the schema descriptor for code field.
	inviteepartyDescCode := inviteepartyFields[1].Descriptor()
	// inviteeparty.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	inviteeparty.CodeValidator = func() func(string) error {
		validators := inviteepartyDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
