// Code generated by entc, DO NOT EDIT.

package invitee

const (
	// Label holds the string label denoting the invitee type in the database.
	Label = "invitee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIsChild holds the string denoting the is_child field in the database.
	FieldIsChild = "is_child"
	// FieldHasPlusOne holds the string denoting the has_plus_one field in the database.
	FieldHasPlusOne = "has_plus_one"
	// FieldIsBridesmaid holds the string denoting the is_bridesmaid field in the database.
	FieldIsBridesmaid = "is_bridesmaid"
	// FieldIsGroomsman holds the string denoting the is_groomsman field in the database.
	FieldIsGroomsman = "is_groomsman"
	// FieldPlusOneName holds the string denoting the plus_one_name field in the database.
	FieldPlusOneName = "plus_one_name"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldAddressLine1 holds the string denoting the address_line_1 field in the database.
	FieldAddressLine1 = "address_line_1"
	// FieldAddressLine2 holds the string denoting the address_line_2 field in the database.
	FieldAddressLine2 = "address_line_2"
	// FieldAddressCity holds the string denoting the address_city field in the database.
	FieldAddressCity = "address_city"
	// FieldAddressState holds the string denoting the address_state field in the database.
	FieldAddressState = "address_state"
	// FieldAddressPostalCode holds the string denoting the address_postal_code field in the database.
	FieldAddressPostalCode = "address_postal_code"
	// FieldAddressCountry holds the string denoting the address_country field in the database.
	FieldAddressCountry = "address_country"
	// FieldRsvpResponse holds the string denoting the rsvp_response field in the database.
	FieldRsvpResponse = "rsvp_response"
	// EdgeParty holds the string denoting the party edge name in mutations.
	EdgeParty = "party"
	// Table holds the table name of the invitee in the database.
	Table = "invitees"
	// PartyTable is the table the holds the party relation/edge.
	PartyTable = "invitees"
	// PartyInverseTable is the table name for the InviteeParty entity.
	// It exists in this package in order to avoid circular dependency with the "inviteeparty" package.
	PartyInverseTable = "invitee_parties"
	// PartyColumn is the table column denoting the party relation/edge.
	PartyColumn = "invitee_party_invitees"
)

// Columns holds all SQL columns for invitee fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIsChild,
	FieldHasPlusOne,
	FieldIsBridesmaid,
	FieldIsGroomsman,
	FieldPlusOneName,
	FieldPhone,
	FieldEmail,
	FieldAddressLine1,
	FieldAddressLine2,
	FieldAddressCity,
	FieldAddressState,
	FieldAddressPostalCode,
	FieldAddressCountry,
	FieldRsvpResponse,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "invitees"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"invitee_party_invitees",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsChild holds the default value on creation for the "is_child" field.
	DefaultIsChild bool
	// DefaultHasPlusOne holds the default value on creation for the "has_plus_one" field.
	DefaultHasPlusOne bool
	// DefaultIsBridesmaid holds the default value on creation for the "is_bridesmaid" field.
	DefaultIsBridesmaid bool
	// DefaultIsGroomsman holds the default value on creation for the "is_groomsman" field.
	DefaultIsGroomsman bool
)
