// Code generated by entc, DO NOT EDIT.

package inviteeparty

const (
	// Label holds the string label denoting the inviteeparty type in the database.
	Label = "invitee_party"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// EdgeInvitees holds the string denoting the invitees edge name in mutations.
	EdgeInvitees = "invitees"
	// Table holds the table name of the inviteeparty in the database.
	Table = "invitee_parties"
	// InviteesTable is the table the holds the invitees relation/edge.
	InviteesTable = "invitees"
	// InviteesInverseTable is the table name for the Invitee entity.
	// It exists in this package in order to avoid circular dependency with the "invitee" package.
	InviteesInverseTable = "invitees"
	// InviteesColumn is the table column denoting the invitees relation/edge.
	InviteesColumn = "invitee_party_invitees"
)

// Columns holds all SQL columns for inviteeparty fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCode,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
)
