// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Invitee is the predicate function for invitee builders.
type Invitee func(*sql.Selector)

// InviteeParty is the predicate function for inviteeparty builders.
type InviteeParty func(*sql.Selector)
